---
name: 🐛 Bug report
description: Fill out this issue form to help us solve your problem
title: "Bug report for Ansible Automation Platform Demo"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem Summary
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.
        Provide a clear and concise description of what the problem is.  Please paste subset of playbook or command output so we can priotize and try to start troubleshooting.