---
name: 📖 Documentation Issue
description: problem with the Ansible Automation Platform Demo documentation?
labels: ["type: documentation"]
body:
  - type: dropdown
    attributes:
      label: Area
      description: To what section of the documentation does this change primarily pertain?
      options:
        - Quick Start / Provsioning
        - Commands
        - Addons
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Changes
      description: "Describe the issue and provide a link to the file(s) affected"
    validations:
      required: true